### ISSUE TITLE
unhandled rejection (TypeError): navigator.getUserMEdia is not a function  in mobile

### ISSUE THREAD

**Issue by najdakka** [diegogurgel/react-webrtc#13]
The application works perfectly on the desktop, but when i try to run the application on a mobile , i get this error :
"unhandled rejection (TypeError): navigator.getUserMEdia is not a function" .

**Comment by diegogurgel** [comment]
It means that your browser doesn't support it. Probably you received this message from a iOS device. You maybe you need to use `navigator.mediaDevices.getUserMedia` instead. I'll also keep this issue open because we need to fix this here also.

**Comment by najdakka** [comment]
No, it's an android phone .
And i did try navigator.mediaDevices.getUserMedia , but still the same probleme.

**Comment by diegogurgel** [comment]
Which version of chrome or firefox are you using there ?

**Comment by najdakka** [comment]
I did find the probleme . getUserMEdia  will throw an error if the page is loaded from insecure origin. We should Use https or localhost .
Thanks for your help
