### ISSUE TITLE
Establishing connection not working on diff devices

### ISSUE THREAD

**Issue by AhmedAbdAlRahmanAnwar** [diegogurgel/react-webrtc#17]
the app is running perfectly on localhost but when deployed on heroku (even with correct stun and turn servers) , the app always keep waiting for someone and never establishing connection.
Note : the app establishes connection only if you open the same link on the same machine on another tab.
i looked at the code and had some observations , at server.js , the port is 8080 , how this is going to work dynamically on online deployment, 
secondly , REACT_APP_SIGNALING_SERVER is always http://localhost:8080 when you pass it at video.js and this also isn't dynamic for online deployment.
i tried to solve this issue but i couldn't, any help will be appreciated.Thanks

**Comment by diegogurgel** [comment]
Did you tried to change your .env to point to your signaling server?

**Comment by AhmedAbdAlRahmanAnwar** [comment]
I tried this and also tried to not use the .env at all throw writing the
servers in the code itself.
i deployed on AWS Amplify but the same problem exists.
Can i Send the edited code and you can take a look at it?
it is the same code as yours, no change in logic, the change is made in
(video.js, server.js, simple-peer.js).

**Comment by diegogurgel** [comment]
Please try to build it before sending to aws.

**Comment by AhmedAbdAlRahmanAnwar** [comment]
your demo link isn't working now.this is weired
