### ISSUE TITLE
Socket problem when deploying to Heroku

### ISSUE THREAD

**Issue by grp06** [diegogurgel/react-webrtc#4]
I cloned the repo, created my turn account as suggested, and it works as expected on localhost. However when I deploy to heroku I get these errors:
![Screen Shot 2020-03-22 at 5 20 19 PM](https://user-images.githubusercontent.com/1573959/77260977-7c399f00-6c61-11ea-9d08-5fd5f1b89569.png)

Any ideas?

**Comment by diegogurgel** [comment]
Maybe heroku is not building the env variables. I was having the same problem with deploying it to zeit(seems they aren't considering .env variables anymore) . Then what I did was send just the build folder. Other solution for that is to try set the env variables on heroku.
