### ISSUE TITLE
Hi!! diegogurgel! i am your fan and i like your webrtc project so... i send you email and... i write here too about my problem

### ISSUE THREAD

**Issue by KneeHunter** [diegogurgel/react-webrtc#8]
hi! my name is seong hun jeong and i am looking at your github repository in react-webrtc. but i have difficulty. it doesnt work in my local....mmmm So i wanna your help. i am running react and git clone your repository react-webrtc. and i run ngrok(because of access permission foreign access allow) but each view is running in each view(for example. user 'A' can watch view of user'A') but user'A' cant watch view of user'B' and user'B' cnat watch user'A'. but your test url is running correctly... i wanna really really your help...

**Comment by diegogurgel** [comment]
Ok Seong. I'll try to help you. Can you paste the error or the screenshot with it? Does it works with ngrok?

**Comment by KneeHunter** [comment]
![Screenshot from 2020-03-30 18-05-06](https://user-images.githubusercontent.com/32152709/77895054-27c19f80-72b1-11ea-924c-5597021aa37d.png)



it doesnt happend error.. but it doesnt work... i can't other person's cam. however both of us typed same room id

**Comment by diegogurgel** [comment]
Did you run ```npm i``` inside ```/server```? and after it go to the project folder and run ```npm run start:local```

**Comment by KneeHunter** [comment]
i am using vmware i dont know how to access External Connection. i use ./ngrok 192.168.174.131.3000 that but it doesnt work

**Comment by diegogurgel** [comment]
I can also try to update the env variables for the signaling server. I replied your email.

**Comment by KneeHunter** [comment]
Thank you!! i checked my email and i send you skype chat!

**Comment by diegogurgel** [comment]
The solution was to change the port to 8080(port that server is running). Just a reminder the server and the FE don't run in the same port using the default configuration(client is running on 3000 and server will be running on 8080 unless you change it).
