### ISSUE TITLE
Not connecting clients from different networks

### ISSUE THREAD

**Issue by diegogurgel** [diegogurgel/react-webrtc#9]
@diegogurgel  I am having issue in video chat. When two clients connected to same network, it working fine. But having issue on connecting with different client. I am running you example code. Anything extra configuration I need to do

_Originally posted by @donny08 in https://github.com/diegogurgel/react-webrtc/issues/7#issuecomment-609437849_

**Comment by diegogurgel** [comment]
Can you tell me where you are running it?

**Comment by AwolDes** [comment]
From a quick look around, it looks like a STUN and/or TURN server need to be configured: https://stackoverflow.com/questions/43992334/why-my-webrtc-connection-works-only-at-local-network

I noticed the demo won't work with separate networks either, so I'm guessing this is the missing piece of the puzzle.

**Comment by diegogurgel** [comment]
Yes, it can be. I'll be investigating this during this week. Last week it was possible to do a call Poland-Korea. Something stopped working or got updated. I also considering that I am using free stun and turn servers and right now the use of those servers have increased

**Comment by diegogurgel** [comment]
I'm noticing the same problem with other webrtc demos out there.

**Comment by donny08** [comment]
> Can you tell me where you are running it?

I'm running on heroku

**Comment by diegogurgel** [comment]
> > Can you tell me where you are running it?
> 
> I'm running on heroku

Yes I'm having the same problem but I think that is something related to turn and stun server not with the application itself. I also asked about that on simple-peer repository because I saw that other applications are having the same problem.

**Comment by diegogurgel** [comment]
I was able to solve it by testing my stun and turn servers here https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
in my case, I was getting unauthorized. I just created a new turn user 😅 

I deployed the updated version check it out
https://react-webrtc-build.dgurgel.now.sh
